In [3]:
#pip install numpy
import numpy as np

In [4]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
b=np.array([[1,2,3,4],[1,2,3,4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
a.ndim #dimensions

1

In [8]:
b.ndim #dimensions

2

In [10]:
b.shape #(rows,columns)

(2, 4)

In [12]:
b.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
a.nbytes

16

In [15]:
c=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
c

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [17]:
c[0,1]

2

In [18]:
c[1,1]

2

In [19]:
c[1,3] #(r,c)

4

In [20]:
c[0,:] #total row

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
c[:,2]#specific total col

array([3, 3])

In [22]:
d=np.array([[[1,2],[2,3],[3,4],[5,6]]])
d

array([[[1, 2],
        [2, 3],
        [3, 4],
        [5, 6]]])

In [23]:
d.ndim

3

In [24]:
s=np.zeros((2,3))
s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
s=np.ones((2,3))
s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
s=np.ones((2,3,4))
s

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [27]:
d=np.full((2,3),99)
d

array([[99, 99, 99],
       [99, 99, 99]])

In [28]:
f=np.random.rand(4,2)
f

array([[0.32764663, 0.41948615],
       [0.57931043, 0.40470683],
       [0.02751488, 0.10660482],
       [0.07334266, 0.56318437]])

In [29]:
f=np.random.rand(4,2)
f

array([[0.20602719, 0.86520217],
       [0.39347695, 0.0627989 ],
       [0.99018733, 0.45285792],
       [0.77263617, 0.61163542]])

In [30]:
c=np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a=np.array([1,2,3,4])
b=a
b

array([1, 2, 3, 4])

In [33]:
a=np.array([1,2,3,4])
b=a
b[0]=12
a

array([12,  2,  3,  4])

In [34]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=12
a

array([1, 2, 3, 4])

In [35]:
a=np.array([1,2,3,4])

In [36]:
a+2

array([3, 4, 5, 6])

In [37]:
a-2

array([-1,  0,  1,  2])

In [38]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [39]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [40]:
a//2

array([0, 1, 1, 2], dtype=int32)